[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.20"
optimizer_runs = 200
optimizer_details = {peephole = true, jumpdestRemover = true, orderLiterals = true, deduplicate = true, cse = true, constantOptimizer = true, yul = true, yulDetails = {stackAllocation = true, optimizerSteps = "dhfoDgvulfnTOE"}}

[profile.test]
fuzz = { runs = 1000 }
invariant = { runs = 100, depth = 100 }
